CALCULATIONS WITH MISSING VALUES --

In [1]:
#24-FEB
import pandas as pd
import numpy as np
df=pd.DataFrame({'A':[1,2,np.nan],'B':['a',np.nan,'c'],'C':[10,np.nan,np.nan]})
print(df)

     A    B     C
0  1.0    a  10.0
1  2.0  NaN   NaN
2  NaN    c   NaN

In [2]:
#isnull()
print(df['A'].isnull())

0    False
1    False
2     True
Name: A, dtype: bool

In [3]:
#ISNULL()
#NOTNULL()
df=pd.DataFrame(np.random.randn(5,3),index=['a','b','c','d','e'],columns=['one','two','three'])
print(df)
df=df.reindex(['p','b','c','d','q'])
print(df.isnull())
print(df.notnull())

        one       two     three
a -0.363884 -0.335853 -1.611582
b  0.730690 -1.391420 -1.269513
c  1.782106  0.190313  0.739957
d -1.330532 -0.061400 -0.765338
e -2.074958 -1.204099 -1.259711
     one    two  three
p   True   True   True
b  False  False  False
c  False  False  False
d  False  False  False
q   True   True   True
     one    two  three
p  False  False  False
b   True   True   True
c   True   True   True
d   True   True   True
q  False  False  False

In [4]:
#SUM()
import pandas as pd
import numpy as np
df=pd.DataFrame({'A':[1,2,np.nan],'B':['a',np.nan,'c'],'C':[10,np.nan,np.nan]})
print(df)
print(df['A'].sum())
print(df['B'].sum())
print(df['C'].sum())

     A    B     C
0  1.0    a  10.0
1  2.0  NaN   NaN
2  NaN    c   NaN
3.0
ac
10.0

In [5]:
#COUNT()
print(df['A'].count())
print(df['B'].count())
print(df['C'].count())
print(df.value_counts())   # returns the count of not null row wise
print(df.count())          # counts ths not null column wise

2
2
1
A    B  C
1.0  a  10.0    1
Name: count, dtype: int64
A    2
B    2
C    1
dtype: int64

In [6]:
# FILL()
df=pd.DataFrame({'A':[1,2,3],'B':['a',np.nan,'c'],'C':[10,np.nan,20]})
df1=df.fillna(value='Cat')
print(df1)

   A    B     C
0  1    a  10.0
1  2  Cat   Cat
2  3    c  20.0

In [7]:
#DROPNA()
df=pd.DataFrame({'A':[1,2,3],'B':['a',np.nan,'c'],'C':[10,np.nan,np.nan]})
print(df)
print(df.dropna())

   A    B     C
0  1    a  10.0
1  2  NaN   NaN
2  3    c   NaN
   A  B     C
0  1  a  10.0

In [8]:
#25-FEB
#fillna()
df=pd.DataFrame({'A':[1,2,3],'B':['a',np.nan,'c'],'C':[10,np.nan,np.nan]})
print(df.fillna(3))

   A  B     C
0  1  a  10.0
1  2  3   3.0
2  3  c   3.0

In [9]:
#filling mean or sum values of the column in place of nan 
print(df['A'].fillna(value=df['A'].mean()))
print(df['A'].fillna(value=df['A'].sum()))

0    1
1    2
2    3
Name: A, dtype: int64
0    1
1    2
2    3
Name: A, dtype: int64

In [10]:
#print(df.fillna(value=df['A'].mean()))
print(df.fillna(value=df['C'].mean()))

   A     B     C
0  1     a  10.0
1  2  10.0  10.0
2  3     c  10.0

In [11]:
#thresh() with drop()  thresh- counts least not null value in a column to remove 
df=pd.DataFrame({'A':[1,2,np.nan],'B':[4,5,10],'C':[10,np.nan,np.nan]})
print(df,"\n\n")
print(df.dropna(thresh=2))

     A   B     C
0  1.0   4  10.0
1  2.0   5   NaN
2  NaN  10   NaN


     A  B     C
0  1.0  4  10.0
1  2.0  5   NaN

In [12]:
#REPLACE FUNC
df=pd.DataFrame({'one':[10,20,30,40,50,2000], 'two':[1000,0,30,20,40,50]})
print(df,"\n\n")
print(df.replace({1000:10,2000:0}))

    one   two
0    10  1000
1    20     0
2    30    30
3    40    20
4    50    40
5  2000    50


   one  two
0   10   10
1   20    0
2   30   30
3   40   20
4   50   40
5    0   50

GROUPBY() 
1. aggregation   - computing a summary statics
2. transformation  - perform some group-specific operation
3. filteration   - discarding the data with some condition

In [13]:
import pandas as pd
ipl_data={'Team':['Riders','Riders','Devils','Devils','Kings','Kings','Kings','Kings','Riders','Royals','Royals','Riders'],
          'Rank':[1,2,2,3,3,4,1,1,2,4,1,2],
          'Year':[2014,2015,2014,2015,2014,2015,2016,2017,2016,2014,2015,2017],
          'points':[876,789,863,673,741,812,756,788,694,701,804,690]}
df = pd.DataFrame(ipl_data)
print(df)

      Team  Rank  Year  points
0   Riders     1  2014     876
1   Riders     2  2015     789
2   Devils     2  2014     863
3   Devils     3  2015     673
4    Kings     3  2014     741
5    Kings     4  2015     812
6    Kings     1  2016     756
7    Kings     1  2017     788
8   Riders     2  2016     694
9   Royals     4  2014     701
10  Royals     1  2015     804
11  Riders     2  2017     690

In [14]:
#Splitting data into groups
df1=df.groupby('Year').groups
print(df1,"\n\n")
df2=df.groupby('Team').groups
print(df2,"\n\n")
df3=df.groupby('Rank').groups
print(df3)

{2014: [0, 2, 4, 9], 2015: [1, 3, 5, 10], 2016: [6, 8], 2017: [7, 11]}


{'Devils': [2, 3], 'Kings': [4, 5, 6, 7], 'Riders': [0, 1, 8, 11], 'Royals': [9, 10]}


{1: [0, 6, 7, 10], 2: [1, 2, 8, 11], 3: [3, 4], 4: [5, 9]}

In [ ]:
#df1=df.groupby('Team').max()
#print(df1, "\n\n")
df2=df.groupby('Year').max()
print(df2)

In [1]:
# 26-FEB
import pandas as pd
ipl_data={'Team':['Riders','Riders','Devils','Devils','Kings','Kings','Kings','Kings','Riders','Royals','Royals','Riders'],
          'Rank':[1,2,2,3,3,4,1,1,2,4,1,2],
          'Year':[2014,2015,2014,2015,2014,2015,2016,2017,2016,2014,2015,2017],
          'points':[876,789,863,673,741,812,756,788,694,701,804,690]}
df = pd.DataFrame(ipl_data)
df1=df.groupby('Team').max()['points']
print(df1)

Team
Devils    863
Kings     812
Riders    876
Royals    804
Name: points, dtype: int64

In [2]:
df1=df.groupby('Year')['Rank'].mean()
print(df1)
df2=df.groupby('Year')['Rank'].count()
print(df2)
df3=df.groupby('Year')['Rank'].sum()
print(df3)
df4=df.groupby('Year')['Rank'].std()
print(df4)

Year
2014    2.5
2015    2.5
2016    1.5
2017    1.5
Name: Rank, dtype: float64
Year
2014    4
2015    4
2016    2
2017    2
Name: Rank, dtype: int64
Year
2014    10
2015    10
2016     3
2017     3
Name: Rank, dtype: int64
Year
2014    1.290994
2015    1.290994
2016    0.707107
2017    0.707107
Name: Rank, dtype: float64

In [3]:
df1=df.groupby('Year')['Rank'].agg(["std","mean","max"])
print(df1)

           std  mean  max
Year
2014  1.290994   2.5    4
2015  1.290994   2.5    4
2016  0.707107   1.5    2
2017  0.707107   1.5    2

In [4]:
#score=lambda x:(x+10)
grouped=df.groupby('Team')
score=lambda x: (x+10)               #adding 10 to each rank, eg: 1+10 =11 
print(grouped.transform(score))

    Rank  Year  points
0     11  2024     886
1     12  2025     799
2     12  2024     873
3     13  2025     683
4     13  2024     751
5     14  2025     822
6     11  2026     766
7     11  2027     798
8     12  2026     704
9     14  2024     711
10    11  2025     814
11    12  2027     700

In [5]:
grouped=df.groupby('Team')
score=lambda x: (x+10)               #adding 10 to each rank, eg: 1+10 =11 
print(grouped['points'].transform(score))

0     886
1     799
2     873
3     683
4     751
5     822
6     766
7     798
8     704
9     711
10    814
11    700
Name: points, dtype: int64

In [6]:
#team count should be 3  more than 3
print(df.groupby('Team').filter(lambda x: len(x) >= 3))

      Team  Rank  Year  points
0   Riders     1  2014     876
1   Riders     2  2015     789
4    Kings     3  2014     741
5    Kings     4  2015     812
6    Kings     1  2016     756
7    Kings     1  2017     788
8   Riders     2  2016     694
11  Riders     2  2017     690

In [43]:
#27-FEB
import pandas as pd
df=pd.read_csv("C:\\Users\\Lenovo\\downloads\\imdb_data.csv",encoding='latin-1') #encoding='utf-8'
print(df)

      ï»¿id                              belongs_to_collection    budget  \
0         1  [{'id': 313576, 'name': 'Hot Tub Time Machine ...  14000000
1         2  [{'id': 107674, 'name': 'The Princess Diaries ...  40000000
2         3                                                NaN   3300000
3         4                                                NaN   1200000
4         5                                                NaN         0
...     ...                                                ...       ...
2995   2996                                                NaN         0
2996   2997                                                NaN         0
2997   2998                                                NaN  65000000
2998   2999                                                NaN  42000000
2999   3000                                                NaN  35000000

                                                 genres  \
0                        [{'id': 35, 'name': 'Comedy'}]
1     [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...
2                         [{'id': 18, 'name': 'Drama'}]
3     [{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...
4     [{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...
...                                                 ...
2995  [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...
2996  [{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...
2997  [{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...
2998  [{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...
2999  [{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...

                               homepage    imdb_id original_language  \
0                                   NaN  tt2637294                en
1                                   NaN  tt0368933                en
2     http://sonyclassics.com/whiplash/  tt2582802                en
3            http://kahaanithefilm.com/  tt1821480                hi
4                                   NaN  tt1380152                ko
...                                 ...        ...               ...
2995                                NaN  tt0109403                en
2996                                NaN  tt2364975                sv
2997                                NaN  tt0116908                en
2998     http://www.alongcamepolly.com/  tt0343135                en
2999   http://www.abductionthefilm.com/  tt1600195                en

                                original_title  \
0                       Hot Tub Time Machine 2
1     The Princess Diaries 2: Royal Engagement
2                                     Whiplash
3                                      Kahaani
4                                 ë§ë¦°ë³´ì´
...                                        ...
2995                                   Chasers
2996                             Vi Ã¤r bÃ¤st!
2997                   The Long Kiss Goodnight
2998                          Along Came Polly
2999                                 Abduction

                                               overview  popularity  ...  \
0     When Lou, who has become the "father of the In...    6.575393  ...
1     Mia Thermopolis is now a college graduate and ...    8.248895  ...
2     Under the direction of a ruthless instructor, ...   64.299990  ...
3     Vidya Bagchi (Vidya Balan) arrives in Kolkata ...    3.174936  ...
4     Marine Boy is the story of a former national s...    1.148070  ...
...                                                 ...         ...  ...
2995  Military men Rock Reilly and Eddie Devane are ...    9.853270  ...
2996  Three girls in 1980s Stockholm decide to form ...    3.727996  ...
2997  Samantha Caine, suburban homemaker, is the ide...   14.482345  ...
2998  Reuben Feffer is a guy who's spent his entire ...   15.725542  ...
2999  A young man sets out to uncover the truth abou...   10.512109  ...

     release_date runtime                                   spoken_languages  \
0         2/20/15    93.0           [{'iso_639_1': 'en', 'name': 'English'}]
1      08-06-2004   113.0           [{'iso_639_1': 'en', 'name': 'English'}]
2      10-10-2014   105.0           [{'iso_639_1': 'en', 'name': 'English'}]
3      03-09-2012   122.0  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...
4      02-05-2009   118.0  [{'iso_639_1': 'ko', 'name': 'íêµ­ì´/ì¡°ì ...
...           ...     ...                                                ...
2995      4/22/94   102.0           [{'iso_639_1': 'en', 'name': 'English'}]
2996      3/28/13   102.0           [{'iso_639_1': 'sv', 'name': 'svenska'}]
2997   10-11-1996   120.0           [{'iso_639_1': 'en', 'name': 'English'}]
2998      1/16/04    90.0           [{'iso_639_1': 'en', 'name': 'English'}]
2999      9/22/11   106.0           [{'iso_639_1': 'en', 'name': 'English'}]

        status                                            tagline  \
0     Released  The Laws of Space and Time are About to be Vio...
1     Released  It can take a lifetime to find true love; she'...
2     Released    The road to greatness can take you to the edge.
3     Released                                                NaN
4     Released                                                NaN
...        ...                                                ...
2995  Released  It was supposed to be a routine prisoner trans...
2996  Released                                                NaN
2997  Released               What's forgotten is not always gone.
2998  Released  For the most cautious man on Earth, life is ab...
2999  Released          They stole his life. He's taking it back.

                                         title  \
0                       Hot Tub Time Machine 2
1     The Princess Diaries 2: Royal Engagement
2                                     Whiplash
3                                      Kahaani
4                                   Marine Boy
...                                        ...
2995                                   Chasers
2996                          We Are the Best!
2997                   The Long Kiss Goodnight
2998                          Along Came Polly
2999                                 Abduction

                                               Keywords  \
0     [{'id': 4379, 'name': 'time travel'}, {'id': 9...
1     [{'id': 2505, 'name': 'coronation'}, {'id': 42...
2     [{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...
3     [{'id': 10092, 'name': 'mystery'}, {'id': 1054...
4                                                   NaN
...                                                 ...
2995  [{'id': 378, 'name': 'prison'}, {'id': 572, 'n...
2996  [{'id': 1192, 'name': 'sweden'}, {'id': 4470, ...
2997  [{'id': 441, 'name': 'assassination'}, {'id': ...
2998  [{'id': 966, 'name': 'beach'}, {'id': 2676, 'n...
2999  [{'id': 591, 'name': 'cia'}, {'id': 822, 'name...

                                                   cast  \
0     [{'cast_id': 4, 'character': 'Lou', 'credit_id...
1     [{'cast_id': 1, 'character': 'Mia Thermopolis'...
2     [{'cast_id': 5, 'character': 'Andrew Neimann',...
3     [{'cast_id': 1, 'character': 'Vidya Bagchi', '...
4     [{'cast_id': 3, 'character': 'Chun-soo', 'cred...
...                                                 ...
2995  [{'cast_id': 2, 'character': 'Rock Reilly', 'c...
2996  [{'cast_id': 5, 'character': 'Bobo', 'credit_i...
2997  [{'cast_id': 10, 'character': 'Samantha Caine ...
2998  [{'cast_id': 8, 'character': 'Reuben Feffer', ...
2999  [{'cast_id': 2, 'character': 'Nathan Harper', ...

                                                   crew    revenue
0     [{'credit_id': '59ac067c92514107af02c8c8', 'de...   12314651
1     [{'credit_id': '52fe43fe9251416c7502563d', 'de...   95149435
2     [{'credit_id': '54d5356ec3a3683ba0000039', 'de...   13092000
3     [{'credit_id': '52fe48779251416c9108d6eb', 'de...   16000000
4     [{'credit_id': '52fe464b9251416c75073b43', 'de...    3923970
...                                                 ...        ...
2995  [{'credit_id': '52fe4494c3a368484e02ac7d', 'de...    1596687
2996  [{'credit_id': '5716b72ac3a3686678012c84', 'de...     180590
2997  [{'credit_id': '52fe443a9251416c7502d579', 'de...   89456761
2998  [{'credit_id': '556f817b9251410866000a63', 'de...  171963386
2999  [{'credit_id': '5391990d0e0a260fb5001629', 'de...   82087155

[3000 rows x 23 columns]

In [8]:
df.shape

(3000, 23)

In [9]:
df.describe()

             ï»¿id        budget   popularity      runtime       revenue
count  3000.000000  3.000000e+03  3000.000000  2998.000000  3.000000e+03
mean   1500.500000  2.253133e+07     8.463274   107.856571  6.672585e+07
std     866.169729  3.702609e+07    12.104000    22.086434  1.375323e+08
min       1.000000  0.000000e+00     0.000001     0.000000  1.000000e+00
25%     750.750000  0.000000e+00     4.018053    94.000000  2.379808e+06
50%    1500.500000  8.000000e+06     7.374861   104.000000  1.680707e+07
75%    2250.250000  2.900000e+07    10.890983   118.000000  6.891920e+07
max    3000.000000  3.800000e+08   294.337037   338.000000  1.519558e+09

In [10]:
# 3rd movie details
df.iloc[2]

ï»¿id                                                                    3
belongs_to_collection                                                  NaN
budget                                                             3300000
genres                                       [{'id': 18, 'name': 'Drama'}]
homepage                                 http://sonyclassics.com/whiplash/
imdb_id                                                          tt2582802
original_language                                                       en
original_title                                                    Whiplash
overview                 Under the direction of a ruthless instructor, ...
popularity                                                        64.29999
poster_path                               /lIv1QinFqz4dlp5U4lQ6HaiskOZ.jpg
production_companies     [{'name': 'Bold Films', 'id': 2266}, {'name': ...
production_countries     [{'iso_3166_1': 'US', 'name': 'United States o...
release_date                                                    10-10-2014
runtime                                                              105.0
spoken_languages                  [{'iso_639_1': 'en', 'name': 'English'}]
status                                                            Released
tagline                    The road to greatness can take you to the edge.
title                                                             Whiplash
Keywords                 [{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...
cast                     [{'cast_id': 5, 'character': 'Andrew Neimann',...
crew                     [{'credit_id': '54d5356ec3a3683ba0000039', 'de...
revenue                                                           13092000
Name: 2, dtype: object

In [11]:
# specific detail 
df.iloc[2]['original_title']

'Whiplash'

In [2]:
#specific detail 
df.iloc[6]['original_title']

'The Possession'

In [3]:
#specific detail 
df.iloc[9]['original_title']

'A Mighty Wind'

In [ ]:
#9-MAR
import pandas as pd
df.sort_values('revenue',ascending=False)[['title','revenue']].head(1)

             title     revenue
1126  The Avengers  1519557910

In [44]:
df.sort_values('revenue',ascending=False)[['title','revenue']].iloc[1]

title       Furious 7
revenue    1506249360
Name: 1761, dtype: object

In [45]:
#df.isnull()['keywords'].value_counts()
#df['keywords'].isnull().values_counts()

In [17]:
#what is the average revenue of movies
print(df['revenue'].mean())

66725851.88866667

In [18]:
print(df['runtime'].mean())

107.85657104736491

In [19]:
#what is the average revenue of movie released 
df.groupby('status')[['revenue','title']].max()

             revenue                                           title
status
Released  1519557910                                  ÐÐ¾ÑÐ¾Ð»ÑÐ²
Rumored     13418091  The Swan Princess: Escape from Castle Mountain

In [46]:
#to change the format of date column

df['release_date'] = pd.to_datetime(df['release_date'])
df

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_15540\3090522062.py:3: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['release_date'] = pd.to_datetime(df['release_date'])

,ï»¿id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,2015-02-20,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,2004-08-06,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,2014-10-10,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,2012-03-09,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,ë§ë¦°ë³´ì´,Marine Boy is the story of a former national s...,1.148070,...,2009-02-05,118.0,"[{'iso_639_1': 'ko', 'name': 'íêµ­ì´/ì¡°ì ...",Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,2996,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",NaN,tt0109403,en,Chasers,Military men Rock Reilly and Eddie Devane are ...,9.853270,...,1994-04-22,102.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It was supposed to be a routine prisoner trans...,Chasers,"[{'id': 378, 'name': 'prison'}, {'id': 572, 'n...","[{'cast_id': 2, 'character': 'Rock Reilly', 'c...","[{'credit_id': '52fe4494c3a368484e02ac7d', 'de...",1596687
2996,2997,NaN,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...",NaN,tt2364975,sv,Vi Ã¤r bÃ¤st!,Three girls in 1980s Stockholm decide to form ...,3.727996,...,2013-03-28,102.0,"[{'iso_639_1': 'sv', 'name': 'svenska'}]",Released,NaN,We Are the Best!,"[{'id': 1192, 'name': 'sweden'}, {'id': 4470, ...","[{'cast_id': 5, 'character': 'Bobo', 'credit_i...","[{'credit_id': '5716b72ac3a3686678012c84', 'de...",180590
2997,2998,NaN,65000000,"[{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...",NaN,tt0116908,en,The Long Kiss Goodnight,"Samantha Caine, suburban homemaker, is the ide...",14.482345,...,1996-10-11,120.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,What's forgotten is not always gone.,The Long Kiss Goodnight,"[{'id': 441, 'name': 'assassination'}, {'id': ...","[{'cast_id': 10, 'character': 'Samantha Caine ...","[{'credit_id': '52fe443a9251416c7502d579', 'de...",89456761
2998,2999,NaN,42000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",http://www.alongcamepolly.com/,tt0343135,en,Along Came Polly,Reuben Feffer is a guy who's spent his entire ...,15.725542,...,2004-01-16,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"For the most cautious man on Earth, life is ab...",Along Came Polly,"[{'id': 966, 'name': 'beach'}, {'id': 2676, 'n...","[{'cast_id': 8, 'character': 'Reuben Feffer', ...","[{'credit_id': '556f817b9251410866000a63', 'de...",171963386
2999,3000,NaN,35000000,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",http://www.abductionthefilm.com/,tt1600195,en,Abduction,A young man sets out to uncover the truth abou...,10.512109,...,2011-09-22,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,They stole his life. He's taking it back.,Abduction,"[{'id': 591, 'name': 'cia'}, {'id': 822, 'name...","[{'cast_id': 2, 'character': 'Nathan Harper', ...","[{'credit_id': '5391990d0e0a260fb5001629', 'de...",82087155

In [47]:
#first and last movie released
df.sort_values('release_date')[['title','release_date']].iloc[[0,-1]]

                 title release_date
1480  Sunset Boulevard   1950-08-10
1336   Rooster Cogburn   2075-10-17

In [1]:
# 11- MAR
import pandas as pd
df=pd.read_csv("C:\\Users\\Lenovo\\downloads\\ds_salaries.csv",encoding='latin-1') #encoding='utf-8'
print(df)

     Unnamed: 0  work_year experience_level employment_type  \
0             0       2020               MI              FT
1             1       2020               SE              FT
2             2       2020               SE              FT
3             3       2020               MI              FT
4             4       2020               SE              FT
..          ...        ...              ...             ...
602         602       2022               SE              FT
603         603       2022               SE              FT
604         604       2022               SE              FT
605         605       2022               SE              FT
606         606       2022               MI              FT

                      job_title  salary salary_currency  salary_in_usd  \
0                Data Scientist   70000             EUR          79833
1    Machine Learning Scientist  260000             USD         260000
2             Big Data Engineer   85000             GBP         109024
3          Product Data Analyst   20000             USD          20000
4     Machine Learning Engineer  150000             USD         150000
..                          ...     ...             ...            ...
602               Data Engineer  154000             USD         154000
603               Data Engineer  126000             USD         126000
604                Data Analyst  129000             USD         129000
605                Data Analyst  150000             USD         150000
606                AI Scientist  200000             USD         200000

    employee_residence  remote_ratio company_location company_size
0                   DE             0               DE            L
1                   JP             0               JP            S
2                   GB            50               GB            M
3                   HN             0               HN            S
4                   US            50               US            L
..                 ...           ...              ...          ...
602                 US           100               US            M
603                 US           100               US            M
604                 US             0               US            M
605                 US           100               US            M
606                 IN           100               US            L

[607 rows x 12 columns]

In [2]:
df.shape

(607, 12)

In [ ]:
df.info() # to get all information

<class 'pandas.DataFrame'>
RangeIndex: 607 entries, 0 to 606
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          607 non-null    int64
 1   work_year           607 non-null    int64
 2   experience_level    607 non-null    str
 3   employment_type     607 non-null    str
 4   job_title           607 non-null    str
 5   salary              607 non-null    int64
 6   salary_currency     607 non-null    str
 7   salary_in_usd       607 non-null    int64
 8   employee_residence  607 non-null    str
 9   remote_ratio        607 non-null    int64
 10  company_location    607 non-null    str
 11  company_size        607 non-null    str
dtypes: int64(5), str(7)
memory usage: 57.0 KB

In [5]:
df.head()

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,0,2020,MI,FT,Data Scientist,70000,EUR,79833,DE,0,DE,L
1,1,2020,SE,FT,Machine Learning Scientist,260000,USD,260000,JP,0,JP,S
2,2,2020,SE,FT,Big Data Engineer,85000,GBP,109024,GB,50,GB,M
3,3,2020,MI,FT,Product Data Analyst,20000,USD,20000,HN,0,HN,S
4,4,2020,SE,FT,Machine Learning Engineer,150000,USD,150000,US,50,US,L

In [8]:
#find out the avg salary
print(df['salary'].mean())

324000.0626029654

In [10]:
# find the max salary 

print(df.groupby('employment_type')['salary'].max())

employment_type
CT      416000
FL      100000
FT    30400000
PT      400000
Name: salary, dtype: int64

In [ ]:
# count the no. of employee in each employment_type
print(df.groupby('employment_type')['job_title'].count())
#df['employment_type'].value_counts()

employment_type
CT      5
FL      4
FT    588
PT     10
Name: job_title, dtype: int64

In [16]:
# unique job names and total how any unique jobs
print(df['job_title'].unique())
df['job_title'].nunique()

<StringArray>
[                          'Data Scientist',
               'Machine Learning Scientist',
                        'Big Data Engineer',
                     'Product Data Analyst',
                'Machine Learning Engineer',
                             'Data Analyst',
                      'Lead Data Scientist',
                    'Business Data Analyst',
                       'Lead Data Engineer',
                        'Lead Data Analyst',
                            'Data Engineer',
                  'Data Science Consultant',
                          'BI Data Analyst',
                 'Director of Data Science',
                       'Research Scientist',
                 'Machine Learning Manager',
                 'Data Engineering Manager',
 'Machine Learning Infrastructure Engineer',
                              'ML Engineer',
                             'AI Scientist',
                 'Computer Vision Engineer',
                 'Principal Data Scientist',
                     'Data Science Manager',
                             'Head of Data',
            '3D Computer Vision Researcher',
                  'Data Analytics Engineer',
                   'Applied Data Scientist',
                   'Marketing Data Analyst',
                      'Cloud Data Engineer',
                   'Financial Data Analyst',
        'Computer Vision Software Engineer',
             'Director of Data Engineering',
                    'Data Science Engineer',
                  'Principal Data Engineer',
               'Machine Learning Developer',
       'Applied Machine Learning Scientist',
                   'Data Analytics Manager',
                     'Head of Data Science',
                          'Data Specialist',
                           'Data Architect',
                     'Finance Data Analyst',
                   'Principal Data Analyst',
                       'Big Data Architect',
                     'Staff Data Scientist',
                       'Analytics Engineer',
                            'ETL Developer',
                 'Head of Machine Learning',
                             'NLP Engineer',
           'Lead Machine Learning Engineer',
                      'Data Analytics Lead']
Length: 50, dtype: str

50

In [20]:
# top 2 most common jobs
df['job_title'].value_counts().head(2)

job_title
Data Scientist    143
Data Engineer     132
Name: count, dtype: int64

In [ ]:
# all rows with true and false
df['job_title']=='AI Scientist'

0      False
1      False
2      False
3      False
4      False
       ...
602    False
603    False
604    False
605    False
606     True
Name: job_title, Length: 607, dtype: bool

In [ ]:
# rows only with the match
df[df['job_title']=='AI Scientist']

,Unnamed: 0,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
52,52,2020,EN,FT,AI Scientist,300000,DKK,45896,DK,50,DK,S
96,96,2021,EN,PT,AI Scientist,12000,USD,12000,BR,100,US,S
113,113,2021,EN,PT,AI Scientist,12000,USD,12000,PK,100,US,M
244,244,2021,EN,FT,AI Scientist,1335000,INR,18053,IN,100,AS,S
277,277,2021,SE,FT,AI Scientist,55000,USD,55000,ES,100,ES,L
391,391,2022,MI,FT,AI Scientist,120000,USD,120000,US,0,US,M
606,606,2022,MI,FT,AI Scientist,200000,USD,200000,IN,100,US,L

In [ ]:
# heighest salary of AI Scientist
print(df[df['job_title']=='AI Scientist']['salary'].max())

1335000

In [25]:
# heighest salary of AI Scientist with their job_title
print(df[df['job_title']=='AI Scientist'][['salary','job_title']].max())

salary            1335000
job_title    AI Scientist
dtype: object

In [ ]:
# how many job titles are in 2020
df[df['work_year']==2020]['job_title'].count()

np.int64(72)

In [ ]:
# display years
df['work_year'].unique()

array([2020, 2021, 2022])

In [29]:
# each year how many emp
df['work_year'].value_counts()

work_year
2022    318
2021    217
2020     72
Name: count, dtype: int64

In [34]:
# how many emp in US
df[df['company_location']=='US'][['company_location','job_title']].count()

company_location    355
job_title           355
dtype: int64

In [ ]:
df['company_location'].

company_location
US    355
GB     47
CA     30
DE     28
IN     24
FR     15
ES     14
GR     11
JP      6
NL      4
AT      4
PT      4
PL      4
PK      3
AE      3
MX      3
DK      3
LU      3
BR      3
TR      3
AU      3
CN      2
NG      2
IT      2
BE      2
RU      2
SI      2
CH      2
CZ      2
HN      1
HU      1
NZ      1
HR      1
SG      1
RO      1
IQ      1
UA      1
IL      1
MT      1
CL      1
IR      1
CO      1
MD      1
KE      1
VN      1
AS      1
DZ      1
EE      1
MY      1
IE      1
Name: count, dtype: int64